/** @jsx h */
import { h } from 'preact';
import { tw } from '@twind';
import Header from '../components/HeaderComp.tsx';
import Footer from '../components/FooterComp.tsx';
import Card from '../components/Card.tsx';
import { globalStyles } from '../style/globalStyle.ts';
import { PageProps } from '$fresh/server.ts';
import 'https://deno.land/x/dotenv@v3.2.0/load.ts'; // load .env
import QuipComp from '../components/QuipComp.tsx';
import {
	dataBallType,
	IAirtableELement,
	IDataField,
	IMarkdown,
	IQuip,
} from '../utils/types.ts';
import { Marked } from 'https://deno.land/x/markdown@v2.0.0/mod.ts';

interface IQuipContext {
	siteContext: dataBallType;
	quipData: IQuip[];
}

interface IQuipElement {
	id: string;
	createdTime: string;
	fields: IQuip;
}
// interface IQuipField{
// 	Date: string;
//     Post: string;
// }

// Calls need to occur on the route directly and use the handler keyword.
// ref: https://fresh.deno.dev/docs/getting-started/fetching-data
const table = 'SiteContext';
export const handler = {
	async GET(_: any, ctx: any) {
		//   Gather all data from airtable.
		const quipContext: IQuipContext = {} as IQuipContext;
		const quipDataArray: IQuip[] = [];
		const dataBall: dataBallType = {};

		// Fetch the context
		const resp = await fetch(
			`https://api.airtable.com/v0/${
				Deno.env.get('DB_NAME')
			}/${table}?api_key=${Deno.env.get('DB_KEY')}`,
		);
		if (resp.status === 404) {
			return ctx.render(null);
		}
		const res = await resp.json();
		const records = res.records;

		records.forEach(async (e: IAirtableELement) => {
			const key: string = e.fields.Name ? e.fields.Name as string : '';
			const value: IMarkdown = Marked.parse(e.fields.Value)
				? Marked.parse(e.fields.Value)
				: {} as IMarkdown;

			const dataItem: IDataField = {
				Title: e.fields.Title,
				Value: value.content, //text stored in markdown on airtable is converted to HTML here.
				Name: key,
			};

			dataBall[key] = dataItem;
		});
		quipContext.siteContext = dataBall;

		// Fetch the quips

		const quipRes = await fetch(
			`https://api.airtable.com/v0/${
				Deno.env.get('DB_NAME')
			}/Quipper?api_key=${Deno.env.get('DB_KEY')}`,
		);
		if (resp.status === 404) {
			return ctx.render(null);
		}
		const quipResObj = await quipRes.json();
		const quipRecords = quipResObj.records;

		quipRecords.forEach(async (e: IQuipElement) => {
			const post: IMarkdown = Marked.parse(e.fields.Post)
				? Marked.parse(e.fields.Post)
				: {} as IMarkdown;

			const postObject: IQuip = {
				Post: post.content,
				Date: e.createdTime,
			};

			quipDataArray.push(postObject);
		});
		quipContext.quipData = quipDataArray;

		// pass the data object as a prop.
		return ctx.render(quipContext);
	},
};

// the title can be passed directly.
// the actuall content is passed as formatted HTML that is generated by the Markdown engine
export default function Quipper(
	{ data }: PageProps<IQuipContext>,
): h.JSX.Element {
	// console.log('data: ', data);

	return (
		<div class={tw(globalStyles)}>
			<Header title={'The Magic Nacho'} />

			<Card
				contentBody={data.siteContext.quipper.Value}
				contentTitle={data.siteContext.quipper.Title}
			/>

			<QuipComp postArray={data.quipData} />

			<Footer
				content={data.siteContext.footerContent}
				social={data.siteContext.socialLinkSmall}
			/>
		</div>
	);
}
