/** @jsx h */
import { h } from 'preact';
import { tw } from '@twind';
import Header from '../components/HeaderComp.tsx';
import Footer from '../components/FooterComp.tsx';
import Card from '../components/Card.tsx';
import { globalStyles } from '../style/globalStyle.ts';
import { PageProps } from '$fresh/server.ts';
import 'https://deno.land/x/dotenv@v3.2.0/load.ts'; // load .env
import {
	dataBallType,
	IAirtableELement,
	IDataField,
	IMarkdown,
	IQuip,
} from '../utils/types.ts';
import { Marked } from 'https://deno.land/x/markdown@v2.0.0/mod.ts';

interface IQuipperProps {
	postArray: IQuip[];
}
// the title can be passed directly.
// the actuall content is passed as formatted HTML that is generated by the Markdown engine
export default function QuipComp(props: IQuipperProps): h.JSX.Element {
	const day = ['Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat', 'Sun'];

	const contentArray = props.postArray;

	return (
		<section class={'content'}>
			<h2>The Magic Nacho's Quips</h2>
			<div class={'quipper'}>
				{contentArray.map((post) => {
					const postDate = new Date(post.Date);
					return (
						<div class={'quip'}>
							<div id={'date'}>
								{`${
									day[
										postDate.getDay()
									]
								} : ${postDate.getDate()}-${postDate.getMonth()}-${postDate.getFullYear()}`}
							</div>
							<div
								id={'content'}
								dangerouslySetInnerHTML={{ __html: post.Post }}
							/>
						</div>
					);
				})}
			</div>

			{/* <div dangerouslySetInnerHTML={{ __html: body }} /> */}
		</section>
	);
}
